### ISSUE TITLE
Remove docs/ from repository

### ISSUE THREAD

**Issue by runfalk** [Tehmo3/Intervals-In-Node#1]
I might be easier to track things if I start using issues for stuff, so here's one I haven't mentioned by e-mail.

I think the `docs/` directory should not be part of the repository, as it can easily be generated using Grunt? It makes a lot of sense to not include things that can be auto-generated. The reason for this is because it creates a lot of noise when reviewing commits, as well as increasing the overall repository size for no benefit. It can also cause silly merge conflicts that can be tricky to resolve.

**Comment by Tehmo3** [comment]
Good point, I didn't think about that.

Although I am unsure of how to host the docs in this case, as currently they are being hosted via github pages, which requires either a branch or a docs/ directory in the repository.

I think I will use [grunt-gh-pages](https://www.npmjs.com/package/grunt-gh-pages) to automate using the gh-pages branch. Although this might make accepting pull requests awkward/difficult?

Thanks!

**Comment by runfalk** [comment]
Using the gh-pages branch should probably be fine, but it means that you as the repository owner have to update it once you merge or commit something to master. This can possibly be automated using Git hooks.

**Comment by Tehmo3** [comment]
Fixed with 34e04a8acf86662bd90eba501fab0be133cceb16
